import Head from "next/head";
import "./globals.css";
import { Mulish, Raleway } from "next/font/google";
import Script from "next/script";
import WhatsAppButton from "@/components/WhatsAppButton";

export const metadata = {
  metadataBase: new URL("https://tribesforgood.com"),
  title: "TribesforGood: Empowering Gen Z as Young Changemakers",
  description:
    "Explore opportunities in climate action, gender equality, and diversity. Join us to create lasting social impact and drive positive global change. Take action today!",
  keywords: [
    "social impact",
    "community engagement",
    "volunteer opportunities",
    "social change",
    "corporate responsibility",
    "empowering communities",
    "nonprofit collaboration",
    "making a difference",
    "positive change",
    "social innovation",
    "sustainable development",
    "impactful volunteering",
    "global impact",
    "purpose-driven initiative",
  ],
  openGraph: {
    title: "TribesforGood: Empowering Gen Z as Young Changemakers",
    description:
      "Explore opportunities in climate action, gender equality, and diversity. Join us to create lasting social impact and drive positive global change. Take action today!",
    images: [
      {
        url: "/assets/assets/og/home.png", // Path to your image in the public/assets/assets folder
        width: 1200,
        height: 630,
        alt: "Careers at TribesforGood: Join the Movement for Positive Change",
      },
    ],
  },
  icons: {
    icon: "/favicon.ico", // Path to your favicon in the public directory
    shortcut: "/favicon.ico",
    apple: "/favicon.ico", // For Apple touch devices, if needed
  },
};

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--mulish-font",
  weight: ["400", "700"],
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--raleway-font",
  weight: ["400", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon.ico" />
      </Head>
      <body className={`${mulish.variable} ${raleway.variable} antialiased`}>
        <Script
          id="meta-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'/scripts/fb.js');
fbq('init', '3733938190081339');
fbq('track', 'PageView');
            `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=3733938190081339&ev=PageView&noscript=1"
          />
        </noscript>
        {children}
        <WhatsAppButton />
      </body>
    </html>
  );
}
